// <auto-generated/>

namespace ToolBaseDotDev.Pages;

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

/// <summary></summary>
[ResponseCache(
    Duration = 0,
    Location = ResponseCacheLocation.None,
    NoStore = true
)]
public class ErrorModel : PageModel
{
    private readonly ILogger<ErrorModel> _logger;

    /// <summary></summary>
    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

#nullable enable
    /// <summary></summary>
    public string? RequestId { get; set; }
#nullable disable

    /// <summary></summary>
    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    
    /// <summary></summary>
    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}
